# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 54de9c3bdb176c30cc05ea4757ec13a74ff1d0bf6255497243a67d5387b701b35b6346afe157124ec2d0be2783218f2bd0cbf7145382a366e1eee9d23ffd0bae

test:
  secret_key_base: ad2d50dbfc60e6ceae64e161fd2852f90d13aaa5d51c645e36e74611bfbb3e45c383b46b6d467d06b865244262f6f8805e9eb5dd0574d9a2b34f18c5a1a11763

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
